# This script finds the column-wise mean of the centroids generated by the hkmeans scripts
# It then writes this object of shape (1, 600) to disk such that it can be used in the
# second half of step 3.
#
#   Author: Michael Chan (mkc5372)
#   Date:   Feb 2022
#   

import os
import numpy as np
import pdb


# TOP_CENTROID_DIR = '/home/mike/videobert_step3/step3_centroids'
TOP_CENTROID_DIR = '/home/jasonw/step3_full/step3_centroids_full'
AVG_CENTOIRD_DIR = '/home/mike/videobert_step3/step3_average_centroids'


if __name__ == '__main__':
    # Walk through each centroid:
    for root, dir, filenames in os.walk(TOP_CENTROID_DIR):
        for file in filenames:
            centroid = np.load(TOP_CENTROID_DIR + os.path.sep + file)

            # We want to find the column wise mean for the 12 frames within the centroid
            # We can accomplish this using the np.average with axis=0 argument
            centroid_averages = np.average(centroid, axis=0)

            # Save average centroid to new folder
            with open(AVG_CENTOIRD_DIR + os.path.sep + file, 'wb') as infile:
                np.save(infile, centroid_averages)
