# This script finds the average value of the centroids generated by the hkmeans scripts
# It then writes this object of shape (1, 600) to disk such that it can be used in the
# second half of step 3.
#
#   Author: Michael Chan (mkc5372)
#   

import os
import numpy as np
import pdb

TOP_CENTROID_DIR = '/home/mkc5372/hkmeans_outputs/centroids'
AVG_CENTOIRD_DIR = '/home/mkc5372/hkmeans_outputs/avg_centroids'


if __name__ == '__main__':
    # Walk through each centroid:
    for root, dir, filenames in os.walk(TOP_CENTROID_DIR):
        for file in filenames:
            centroid = np.load(TOP_CENTROID_DIR + os.path.sep + file)

            # We want to find the average of the Ith element of each of the 12 frames per centroid
            # We can accomplish this using the np.average with axis=0 argument
            centroid_averages = np.average(centroid, axis=0)

            # Save average centroid to new folder
            with open(AVG_CENTOIRD_DIR + os.path.sep + file, 'wb') as infile:
                np.save(infile, centroid_averages)
